# Generated by Django 4.0.2 on 2022-08-19 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Размер')),
                ('get_mount', models.IntegerField(default=0, verbose_name='Полученные деньги')),
                ('payment_method', models.CharField(choices=[('cards', 'Карты'), ('mobile', 'Мобильный счет'), ('qiwi', 'Qiwi')], default='cards', max_length=20, verbose_name='Способ оплаты')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('closed_date', models.DateTimeField(auto_now=True, verbose_name='Время закрытия')),
                ('status', models.IntegerField(choices=[(-1, 'Платёж отменён❌'), (0, 'Ожидается оплата⏳'), (1, 'Платёж совершён✅')], default=0, verbose_name='Статус')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupon', to='info.coupons', verbose_name='Купон')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player', to='info.players', verbose_name='Игрок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'Список',
            },
        ),
    ]
