# Generated by Django 5.1.3 on 2024-12-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название ссылки')),
                ('link', models.CharField(max_length=50, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'ссылку',
                'verbose_name_plural': 'Ссылки бокового меню',
                'ordering': ['id'],
            },
        ),
    ]
