# Generated by Django 4.0.2 on 2022-08-19 10:01

import apps.shop.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('icon', models.CharField(default='category', max_length=50, verbose_name='Иконка')),
                ('server_name', models.CharField(default='-', max_length=50, verbose_name='Имя сервера')),
                ('number', models.IntegerField(default=apps.shop.models.get_last_number_category, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('check_to_buy', models.CharField(choices=[('have', 'Проверить наличие предмета'), ('-', 'Не нужна проверка'), ('have_more', 'Проверить ценность пермишена')], default='-', max_length=50, verbose_name='Проверка возможности')),
                ('command', models.CharField(help_text='%player% - ник покупателя. %product% - имя товара для команды', max_length=50, verbose_name='Команда выдачи')),
                ('icon', models.CharField(default='category', max_length=50, verbose_name='Иконка')),
                ('number', models.IntegerField(default=apps.shop.models.get_last_number_subcategory, verbose_name='Номер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'подкатегорию',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('category', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('name_for_command', models.CharField(db_index=True, default='-', max_length=50, verbose_name='Имя для команды')),
                ('image', models.ImageField(blank=True, upload_to='products', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(db_index=True, verbose_name='Цена')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('subcategory', 'price'),
            },
        ),
    ]
